# -----------------------------------------------------------------------------
#
#                          Network Configuration Backup
#                              Configuration File
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
#                              Default Settings
# -----------------------------------------------------------------------------

[defaults]
    configs_dir = "$CONFIGS_DIR"
    ipfabric = "https://ipfabric.mycompany.com"
    credentials.username = "$NETWORK_USERNAME"
    credentials.password = "$NETWORK_PASSWORD"

# -----------------------------------------------------------------------------
#
#                          Version Control System(s)
#
# Currently only git systems are supported, but others types may be supported in
# the future.  If you have more than one vcs repository you can include the
# `name` field so that you can identify the vcs-repo using the CLI --name
# option.
# -----------------------------------------------------------------------------

[[git]]
    # the first entry does not require a name and it will be treated
    # as a default; i.e. when the --name option is omitted.
    repo = "https://github.mycorp.com/jschulman/test-network-configs.git"
    token = "$GIT_TOKEN"

[[git]]
    # example of using a deployment key that does not use a passphrase
    name = "demo-ssh"
    repo = "git@gitlab.com:jschulman/test-network-configs.git"
    deploy_key = "$HOME/test-config-backups"

[[git]]
    # example of using a deployment key that uses a passphrase
    name = "demo-ssh-pw"
    repo = "git@github.mlbam.net:jschulman/test-network-configs.git"
    deploy_key = "$HOME/pwtest-backups"
    deploy_passphrase = "$GITKEY_PASSWORD"


# -----------------------------------------------------------------------------
#
#                                Logging
#
# Logging - follows Python format as described
#   https://docs.python.org/3/library/logging.config.html
# -----------------------------------------------------------------------------

[logging.loggers.netcfgbu]
    handlers = ["console", "file"]
    level = "INFO"

[logging.handlers.console]
    class = "logging.StreamHandler"
    formatter = "basic"
    stream = "ext://sys.stdout"

[logging.handlers.file]
    class = "logging.FileHandler"
    formatter = "basic"
    filename =  "ipfnetcfgbu.log"

[logging.formatters.basic]
    format = "%(asctime)s %(levelname)s: %(message)s"
